CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_POINTING=y

# Zephyr 4.1 + Zephyr SDK 0.17.4 currently fails to compile this config with
# toolchain Picolibc because of lock symbol type conflicts. Newlib is provided
# by the same SDK and avoids that mismatch.
CONFIG_NEWLIB_LIBC=y
